flask_lib/books/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange


class BookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=0, max=100)])
    author = StringField('Author', validators=[DataRequired(), Length(min=0, max=100)])
    pages = IntegerField('Pages', validators=[DataRequired(), NumberRange(min=1)])
    submit = SubmitField('Add')


class LendForm(FlaskForm):
    username = StringField('Username', validators=[Length(min=2, max=20)])
    remember = BooleanField('Guest')
    submit = SubmitField('Lend')


class SearchForm(FlaskForm):
    author = StringField('Author', default='')
    title = StringField('Title', default='')
    submit = SubmitField('Search')

flask_lib/books/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from flask_lib import db
from flask_lib.books.forms import SearchForm, BookForm, LendForm
from flask_lib.models import User, Library, Book, BCopy, History
from flask_login import current_user, login_required
from datetime import datetime

books = Blueprint('books', __name__)


@books.route('/book/list', methods=['GET', 'POST'])
@login_required
def book_list():
    page = request.args.get('page', 1, type=int)
    book = Book.query
    form = SearchForm()
    if form.validate_on_submit() or request.args.get('page', 1, type=int):
        if request.values.get("author"):
            form.author.data=request.values.get("author")
            search = '%{}%'.format(form.author.data.upper())
            book = book.filter(Book.author.like(search))
        if request.values.get("title"):
            form.title.data = request.values.get("title")
            search = '%{}%'.format(form.title.data.upper())
            book = book.filter(Book.title.like(search))
    book = book.paginate(page=page, per_page=2, error_out=False)
    return render_template('book_list.html', title='Book List', form=form, legend='Book List', books=book)


@books.route('/book/add/<int:book_id>', methods=['GET', 'POST'])
@login_required
def add_book(book_id):
    lib = Library.query.filter_by(owner_id=current_user.id).first()
    original = Book.query.filter_by(id=book_id).first()
    bcopy = BCopy(owner=current_user, part=lib, original=original)
    db.session.add(bcopy)
    db.session.commit()
    flash('New Book has been added', 'success')
    return redirect(url_for('main.library', lib_id=current_user.Library.id))


@books.route('/book/new', methods=['GET', 'POST'])
@login_required
def new_book():
    form = BookForm()
    if form.validate_on_submit():
        book = Book(title=form.title.data.upper(), author=form.author.data.upper(), pages=form.pages.data)
        db.session.add(book)
        db.session.commit()
        flash('New Book has been added', 'success')
        return redirect(url_for('books.book_list'))
    return render_template('create_book.html', title='New Book', form=form, legend='New Book')


@books.route('/book/<int:book_id>')
@login_required
def book(book_id):
    book = BCopy.query.get_or_404(book_id)
    lib = Library.query.get_or_404(book.lib_id)
    return render_template('book.html', title=book.original.title, book=book, lib=lib)


@books.route('/book/<int:book_id>/<string:status>', methods=['GET'])
@login_required
def update_book(book_id, status):
    book = BCopy.query.get_or_404(book_id)
    if book.owner != current_user:
        abort(403)
    if status == 'Return':
        book.lend = False
        book.guest = False
        his = History(date=datetime.utcnow(), action='return', book=book, username='guest')
        db.session.commit()
        flash('Your book status has been updated!', 'success')
    if status == 'Reading':
        book.status = status
        book.date = datetime.utcnow()
        db.session.commit()
        flash('Your book status has been updated!', 'success')
    if status == 'Finished':
        if book.status == 'Reading':
            delta = datetime.utcnow()-book.date
            current_user.days += delta.days
        current_user.pages += book.original.pages
        book.status = status
        db.session.commit()
        flash('Your book status has been updated!', 'success')
    return redirect(url_for('books.book', book_id=book.id))


@books.route('/book/<int:book_id>/delete', methods=['POST'])
@login_required
def delete_book(book_id):
    book = BCopy.query.get_or_404(book_id)
    if book.owner != current_user:
        abort(403)
    if book.lend:
        flash('You cant delete this book now.', 'danger')
    else:
        db.session.delete(book)
        db.session.commit()
        flash('Your book has been deleted!', 'success')
    return redirect(url_for('main.library', lib_id=current_user.Library.id))


@books.route('/lend/<int:book_id>', methods=['GET', 'POST'])
@login_required
def lend(book_id):
    form = LendForm()
    if form.validate_on_submit():
        book = BCopy.query.get_or_404(book_id)
        if book.owner != current_user:
            abort(403)
        if form.remember.data:
            book.guest = True
            book.lend = True
            his = History(date=datetime.utcnow(), action='lending', book=book, username='guest')
            db.session.add(his)
            db.session.commit()
            return redirect(url_for('main.library', lib_id=current_user.Library.id))
        else:
            user = User.query.filter_by(username=form.username.data).first()
            if user:
                book.lend = True
                lib = Library.query.filter_by(owner_id=user.id).first()
                Lbook = BCopy(lend_id=book.id, owner=current_user, original=book.original, part=lib)
                his = History(date=datetime.utcnow(), action='lending', book=book, username=user.username)
                db.session.add(Lbook)
                db.session.add(his)
                db.session.commit()
                return redirect(url_for('main.library', lib_id=current_user.Library.id))
            else:
                flash('There is no such user.', 'danger')
    return render_template('lend.html', title='Lend', form=form)


@books.route('/book/<int:book_id>/history')
@login_required
def history(book_id):
    page = request.args.get('page', 1, type=int)
    his = History.query.filter_by(book_id=book_id).paginate(page=page, per_page=5)
    book = BCopy.query.get_or_404(book_id)
    lib = Library.query.get_or_404(book.lib_id)
    if lib.owner != current_user:
        abort(403)
    return render_template('history.html', his=his, book=book)


@books.route('/return/<int:book_id>')
@login_required
def return_book(book_id):
    book = BCopy.query.get_or_404(book_id)
    Obook = BCopy.query.get_or_404(book.lend_id)
    lib = Library.query.get_or_404(book.lib_id)
    if lib.owner != current_user:
        abort(403)
    Obook.lend = False
    # Obook.return_date = datetime.utcnow
    his = History(date=datetime.utcnow(), action='return', book=Obook, username=current_user.username)
    db.session.add(his)
    db.session.delete(book)
    db.session.commit()
    flash('Book has been returned.', 'success')
    return redirect(url_for('main.library', lib_id=current_user.Library.id))

flask_lib/main/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from flask_lib import db
from flask_lib.main.forms import InviteForm
from flask_lib.models import User, Library, BCopy
from flask_login import current_user, login_required

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    main_lib = Library.query.filter_by(owner_id=current_user.id).first()
    # libs = Library.query.filter_by(member=current_user).paginate(page=page, per_page=5)
    libs = current_user.Libraries
    return render_template('home.html', libs=libs, main_lib=main_lib)


@main.route('/library/<int:lib_id>')
@login_required
def library(lib_id):
    page = request.args.get('page', 1, type=int)
    lib = Library.query.get_or_404(lib_id)
    user = lib.owner
    if user != current_user and lib not in current_user.Libraries:
        flash('You cant view this library.', 'danger')
        return redirect(url_for('main.home'))
    books = BCopy.query.filter_by(part=lib).paginate(page=page, per_page=5)
    data = {'Reading': 0, 'Finished': 0, 'Lend': 0, 'New': 0, 'PD': 0}
    for book in books.items:
        if book.lend:
            data['Lend'] += 1
        else:
            data[book.status] += 1
    if user.days > 0:
        data['PD'] = user.pages / user.days
    return render_template('library.html', books=books, lib=lib, data=data)


@main.route('/library/<int:lib_id>/invite', methods=['GET', 'POST'])
@login_required
def invite(lib_id):
    form = InviteForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        lib = Library.query.filter_by(id=lib_id).first()
        if lib.owner != current_user:
            abort(403)
        user.Libraries.append(lib)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('invite.html', title='Invite', form=form)

flask_lib/users/routes.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_lib import db, bcrypt
from flask_lib.models import User, Library
from flask_login import login_user, current_user, logout_user, login_required

from flask_lib.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_lib.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        user.active = True
        db.session.add(user)
        lib = Library(owner=user)
        db.session.add(lib)
        db.session.commit()
        # send_active_email(user)
        login_user(user, remember=False)
        flash('An email has been send to you to active your account.', 'info')
        # db.session.rollback()
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.active:
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Account inactive.', 'danger')
        else:
            flash('Login Unsuccessful.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pic/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # send_reset_email(user)
        flash('An email has been send to reset your password.', 'info')
        token = user.get_token()
        return redirect(url_for('users.reset_token', token=token, _external=True))
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid/expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated', 'success')
        return redirect(url_for('main.home'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/active/<token>', methods=['GET', 'POST'])
def active_token(token):
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid/expired token', 'warning')
        return redirect(url_for('users.register'))
    user.active = True
    db.session.commit()
    login_user(user, remember=False)
    flash(f'Your account has been activated', 'success')
    return redirect(url_for('main.home'))

flask_lib/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h1>about page</h1>
{% endblock content %}

flask_lib/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}

                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask_lib/templates/book.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h1>Title: {{ book.original.title }}</h1>
            <h1>Author: {{ book.original.author }}</h1>
            <h1>Pages: {{ book.original.pages }}</h1>
            <h1>Owner: {{ book.owner.username }}</h1>
            {% if book.lend == True %}
            <h1 class="article-content">Lend</h1>
            {% else %}
            <h1 class="article-content">{{ book.status }}</h1>
            {% endif %}
            {% if lib.owner == current_user %}
            <div>
                <div>
                    {% if book.owner == current_user %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.history', book_id=book.id) }}">History</a>
                    {% endif %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.update_book', book_id=book.id, status='Reading') }}">Reading</a>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.update_book', book_id=book.id, status='Finished') }}">Finish</a>
                </div>
                {% if book.lend and book.guest %}
                <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.update_book', book_id=book.id, status='Return') }}">Return</a>
                </div>
                {% endif %}
                {% if book.lend == False and book.owner == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.lend', book_id=book.id)}}">Lend</a>
                </div>
                <div>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </div>
                {% endif %}
            </div>
                {% if not book.owner == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.return_book', book_id=book.id) }}">Return</a>
                </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
</article>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Book?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('books.delete_book', book_id=book.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask_lib/templates/create_book.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {%  if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {%  for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {%  endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {%  endif %}
            </div>
            <div class="form-group">
                {{ form.author.label(class="form-control-label") }}
                {%  if form.author.errors %}
                    {{ form.author(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {%  for error in form.author.errors %}
                            <span>{{ error }}</span>
                        {%  endfor %}
                    </div>
                {% else %}
                    {{ form.author(class="form-control form-control-lg") }}
                {%  endif %}
            </div>
            <div class="form-group">
                {{ form.pages.label(class="form-control-label") }}
                {%  if form.pages.errors %}
                    {{ form.pages(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {%  for error in form.pages.errors %}
                            <span>{{ error }}</span>
                        {%  endfor %}
                    </div>
                {% else %}
                    {{ form.pages(class="form-control form-control-lg") }}
                {%  endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask_lib/templates/history.html
{% extends "layout.html" %}
{% block content %}
<div class="media-body">
        <h1>{{ book.original.title }}</h1>
        <h1>{{ book.original.author }}</h1>
    </div>
{% for h in his.items %}
<article class="media content-section">
    <div class="media-body">
        <p class="article-content">Lend to: {{ h.username }}</p>
        <p class="article-content">{{ h.date.strftime('%Y-%m-%d') }}</p>
        <p class="article-content">{{ h.action }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in his.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if his.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('books.history', book_id=book.id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('books.history', book_id=book.id, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}
{% endblock content %}

flask_lib/templates/home.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + main_lib.owner.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <h2><a class="article-title" href="{{ url_for('main.library', lib_id=main_lib.id) }}">{{ main_lib.owner.username }} Library</a></h2>
        </div>
    </div>
</article>
{% for lib in libs %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + lib.owner.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <h2><a class="article-title" href="{{ url_for('main.library', lib_id=lib.id) }}">{{ lib.owner.username }} Library</a></h2>
        </div>
    </div>
</article>
{% endfor %}
{% endblock content %}

flask_lib/templates/invite.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Invite</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {%  if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {%  for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {%  endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {%  endif %}

            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>

    </form>
</div>
{% endblock content %}

flask_lib/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css">

    {% if title %}
    <title>Flask Blog - {{title}}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Flask Blog</a>
            <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler"
                    data-target="#navbarToggle" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main class="container" role="main">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        {% block side %}{% endblock %}
        <!--<div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>-->
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

flask_lib/templates/library.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Owner {{ lib.owner.username }}</h1>
{% if lib.owner == current_user %}
<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.invite', lib_id=lib.id) }}">invite</a>
<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('books.book_list') }}">Add book</a>
{% endif %}
{% for book in books.items %}
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{{ url_for('books.book', book_id=book.id) }}">{{ book.original.title }}</a></h2>
        <h2>{{ book.original.author }}</h2>
        {% if book.lend %}
        <p class="article-content">Lend</p>
        {% else %}
        <p class="article-content">{{ book.status }}</p>
        {% endif %}
    </div>
</article>
{% endfor %}
{% for page_num in books.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if books.page == page_num %}
            <a class="btn btn-info mb-4" href="{{url_for('main.library', lib_id=lib.id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{url_for('main.library', lib_id=lib.id, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}
{% endblock content %}

{% block side %}
<div class="col-md-4">
    <div class="content-section">
        <h3>Statistic</h3>
        <ul class="list-group">
            <li class="list-group-item list-group-item-light">Books: {{ books.total }}</li>
            <li class="list-group-item list-group-item-light">New Books: {{ data['New'] }}</li>
            <li class="list-group-item list-group-item-light">Reading Books: {{ data['Reading'] }}</li>
            <li class="list-group-item list-group-item-light">Finished Books: {{ data['Finished'] }}</li>
            <li class="list-group-item list-group-item-light">Lend Books: {{ data['Lend'] }}</li>
            <li class="list-group-item list-group-item-light">Pages per day: {{ data['PD'] }}</li>
            <li class="list-group-item list-group-item-light">Total pages read: {{ lib.owner.pages }}</li>
        </ul>
    </div>
</div>
{% endblock side %}